name: registration_ieee
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_animate: ^4.5.2
  mobile_scanner: ^7.0.0
  qr_scanner_overlay: ^0.0.2
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  hive_ce_generator: ^1.9.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
